package com.llanquihuetour.ui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Clase que representa la interfaz gráfica principal (Bienvenida) de la aplicación.
 * @author Jaime Seguel.
 * @since Semana 8
 */
public class VentanaBienvenida extends JFrame {

    // Elementos de la ventana.
    private JPanel ventanaBienvenida = new JPanel();
    private JLabel lblLogo = new JLabel();
    private JLabel lblDescripcion1 = new JLabel();
    private JLabel lblDescripcion2 = new JLabel();
    private JLabel lblDescripcion3 = new JLabel();
    private JLabel lblDescripcion4 = new JLabel();
    private JButton btnClientes = new JButton();
    private JButton btnEmpresa = new JButton();
    private JButton btnServicios = new JButton();

    /**
     * Constructor de la ventana de bienvenida.
     */
    public VentanaBienvenida() {

        setContentPane(ventanaBienvenida);
        setTitle("Llanquihue Tour App - Menú Principal");
        setSize(600, 500);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        lblLogo.setIcon(new ImageIcon(getClass().getResource("/images/Logo.png")));

        // Botón para abrir la ventana clientes.
        btnClientes.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                VentanaBienvenida.this.setVisible(false);
                new VentanaCliente(VentanaBienvenida.this).setVisible(true);
            }
        });

        // Botón para abrir la ventana empresa.
        btnEmpresa.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                VentanaBienvenida.this.setVisible(false);
                new VentanaEmpresa(VentanaBienvenida.this).setVisible(true);
            }
        });

        // Botón para abrir la ventana servicios.
        btnServicios.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                VentanaBienvenida.this.setVisible(false);
                new VentanaServicios(VentanaBienvenida.this).setVisible(true);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ventanaBienvenida = new JPanel();
        ventanaBienvenida.setLayout(new GridBagLayout());
        ventanaBienvenida.setMaximumSize(new Dimension(600, 500));
        ventanaBienvenida.setMinimumSize(new Dimension(600, 500));
        ventanaBienvenida.setPreferredSize(new Dimension(600, 500));
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ventanaBienvenida.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridheight = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        ventanaBienvenida.add(spacer2, gbc);
        lblLogo = new JLabel();
        lblLogo.setIcon(new ImageIcon(getClass().getResource("/images/Logo.png")));
        lblLogo.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 4;
        gbc.gridheight = 2;
        gbc.insets = new Insets(10, 10, 0, 10);
        ventanaBienvenida.add(lblLogo, gbc);
        lblDescripcion1 = new JLabel();
        lblDescripcion1.setText("Bienvenido al Sistema de Gestión de Llanquihue Tour.");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(10, 10, 2, 10);
        ventanaBienvenida.add(lblDescripcion1, gbc);
        lblDescripcion2 = new JLabel();
        lblDescripcion2.setText("Esta plataforma permite administrar el registro de clientes,");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(2, 10, 2, 10);
        ventanaBienvenida.add(lblDescripcion2, gbc);
        lblDescripcion3 = new JLabel();
        lblDescripcion3.setText("coordinar el personal y recursos internos, y gestionar");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(2, 10, 2, 10);
        ventanaBienvenida.add(lblDescripcion3, gbc);
        lblDescripcion4 = new JLabel();
        lblDescripcion4.setText("los servicios turísticos de la agencia.");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(2, 10, 15, 10);
        ventanaBienvenida.add(lblDescripcion4, gbc);
        btnClientes = new JButton();
        btnClientes.setText("CLIENTES");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaBienvenida.add(btnClientes, gbc);
        btnEmpresa = new JButton();
        btnEmpresa.setText("EMPRESA");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 7;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaBienvenida.add(btnEmpresa, gbc);
        btnServicios = new JButton();
        btnServicios.setText("SERVICIOS");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 7;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaBienvenida.add(btnServicios, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ventanaBienvenida.add(spacer3, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ventanaBienvenida;
    }

}
